// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9z6mDSh9VcKwYfveS5ReiDQQiQg2e6Mc',
    appId: '1:404910094346:web:d2e1ec61f8ba6d56e447f3',
    messagingSenderId: '404910094346',
    projectId: 'taskmanager-9e2b9',
    authDomain: 'taskmanager-9e2b9.firebaseapp.com',
    databaseURL: 'https://taskmanager-9e2b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanager-9e2b9.appspot.com',
    measurementId: 'G-9Q6RL654JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjeictc-jP28xvYKeDGuvJ0i_ia0uWhlo',
    appId: '1:404910094346:android:a958709e3ef62b0ce447f3',
    messagingSenderId: '404910094346',
    projectId: 'taskmanager-9e2b9',
    databaseURL: 'https://taskmanager-9e2b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanager-9e2b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjmA6_6_YsuNbBkr-LKk1SggKjiwCb30',
    appId: '1:404910094346:ios:92d20c68d9d6a64fe447f3',
    messagingSenderId: '404910094346',
    projectId: 'taskmanager-9e2b9',
    databaseURL: 'https://taskmanager-9e2b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanager-9e2b9.appspot.com',
    androidClientId: '404910094346-5qmmlvvnj2d3lu1k1ijpm402apsq6i1k.apps.googleusercontent.com',
    iosClientId: '404910094346-04usrn9in3ifj8lasl23jj4sno80hr0c.apps.googleusercontent.com',
    iosBundleId: 'com.nhom6.taskManager',
  );
}
